n = int(input('Digite um número inteiro: '))
print('Esse numero vezes 1 é igual à: ',n * 1)
print('Esse numero vezes 2 é igual à: ',n * 2)
print('Esse numero vezes 3 é igual à: ',n * 3)
print('Esse numero vezes 4 é igual à: ',n * 4)
print('Esse numero vezes 5 é igual à: ',n * 5)
print('Esse numero vezes 6 é igual à: ',n * 6)
print('Esse numero vezes 7 é igual à: ',n * 7)
print('Esse numero vezes 8 é igual à: ',n * 8)
print('Esse numero vezes 9 é igual à: ',n * 9)
print('Esse numero vezes 10 é igual à: ',n * 10)