nome = str(input('Digite um nome? ')).strip()
up = nome.upper()
print('O nome em maiúsculo: {}'.format(up))
low = nome.lower()
print('O nome em minúsculo: {}'.format(low))
div = nome.split()
jun = ''.join(div)
tamanho = len(jun)
print('O tamanho do nome sem os espaços é de {} caracteres.'.format(tamanho))
tam2 = len(div[0])
print('{} Tem {} caracteres.'.format(div[0], tam2))